import forest from './sgcc-forest.json';
function avg(a:number[]){const v=a.filter(Number.isFinite);return v.length?v.reduce((x,y)=>x+y,0)/v.length:NaN}
function std(a:number[]){const m=avg(a),v=a.filter(Number.isFinite);return v.length?Math.sqrt(v.reduce((s,x)=>s+(x-m)**2,0)/v.length):NaN}
function percentile(a:number[],q:number){const v=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!v.length)return NaN;const pos=(v.length-1)*q,lo=Math.floor(pos),hi=Math.ceil(pos);return v[lo]+(v[hi]-v[lo])*(pos-lo)}
const safe=(a:number,b:number)=>a/Math.max(b,.01);
export function dailyFeatures(dates:string[],values:number[]){
 const x=values.map(v=>Number.isFinite(v)&&v>=0?v:NaN),n=x.length,valid=x.filter(Number.isFinite),mean=avg(x),median=percentile(x,.5),st=std(x),q10=percentile(x,.1),q90=percentile(x,.9),maximum=valid.length?Math.max(...valid):NaN,zero=valid.filter(v=>v<.01).length/Math.max(valid.length,1),missing=x.filter(v=>!Number.isFinite(v)).length/n,first=avg(x.slice(0,180)),last=avg(x.slice(-180)),recent=avg(x.slice(-30)),prev=avg(x.slice(-210,-30));
 const monthmeans=[];for(let i=0;i<n;i+=30)monthmeans.push(avg(x.slice(i,i+30)));
 const weekday:number[]=[],weekend:number[]=[];for(let i=0;i<n;i++)(new Date(dates[i]+'T00:00:00Z').getUTCDay()%6===0?weekend:weekday).push(x[i]);
 let run=0,longest=0;for(const v of x){run=Number.isFinite(v)&&v<.01?run+1:0;longest=Math.max(longest,run)}
 const negative=values.filter(v=>Number.isFinite(v)&&v<0).length/n;
 return [mean,median,st,safe(st,mean),q10,q90,maximum,zero,missing,first,last,safe(last,first),recent,prev,safe(recent,prev),safe(std(monthmeans),avg(monthmeans)),safe(avg(weekday),avg(weekend)),longest,negative];
}
export function predictDaily(features:number[]){const input=[...features.map((v,i)=>Number.isFinite(v)?v:forest.impute[i]),...forest.indicator.map(i=>Number.isFinite(features[i])?0:1)];let probability=0;
 for(const tree of forest.trees){let node=0;while(tree.f[node]>=0)node=input[tree.f[node]]<=tree.t[node]?tree.l[node]:tree.r[node];probability+=tree.p[node]}
 return probability/forest.trees.length;
}
export function parseWideCsv(text:string){const lines=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/),heads=lines.shift()?.split(',')||[];if(heads[0]!=='CONS_NO')throw Error('Expected SGCC daily CSV: CONS_NO followed by date columns');const columns=heads.map((s,i)=>({s:s.trim(),i})).filter(x=>/^\d{4}\/\d{1,2}\/\d{1,2}$/.test(x.s)).sort((a,b)=>Date.parse(a.s)-Date.parse(b.s));if(columns.length<180)throw Error('At least 180 daily date columns are required');const dates=columns.map(x=>{const [y,m,d]=x.s.split('/').map(Number);return `${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`});
 const rows=lines.filter(Boolean).map(line=>{const cells=line.split(','),id=(cells[0]||'').trim();if(!id)throw Error('Account ID is missing');const vals=columns.map(x=>{const s=(cells[x.i]||'').trim(),v=Number(s);return s===''?NaN:Number.isFinite(v)?v:NaN});return{id,values:vals}});if(!rows.length||rows.length>500)throw Error('Upload 1–500 accounts');return{dates,rows};}
export function scoreDaily(csv:string){const {dates,rows}=parseWideCsv(csv);return rows.map(({id,values})=>{const f=dailyFeatures(dates,values),p=predictDaily(f),recent=f[10],base=f[9],category=p>=.7?'High Risk':p>=.2?'Moderate Risk':'Normal Risk';let patterns:string[]=[];if(f[11]<.7)patterns.push('Long-term usage below earlier baseline');if(f[14]<.7)patterns.push('Recent usage drop');if(f[7]>.12)patterns.push('Frequent near-zero days');if(f[8]>.25)patterns.push('Substantial gaps in meter history');if(f[3]>1)patterns.push('High variation in daily consumption');if(!patterns.length)patterns=['No simple threshold flag; review the complete history'];return{account_id:id,risk_level:category,risk_score:Number(p.toFixed(5)),class_confidence:Number((p>=.5?p:1-p).toFixed(5)),probabilities:{'Published theft label':p,'Published normal label':1-p},patterns,reading_count:values.filter(Number.isFinite).length,baseline_kwh:Number(base.toFixed(3)),recent_kwh:Number(recent.toFixed(3)),change_percent:Number(((recent/Math.max(base,.01)-1)*100).toFixed(1)),daily_consumption:dates.slice(-180).map((d,i)=>[d,Number.isFinite(values[values.length-180+i])?values[values.length-180+i]:0]),first_reading:dates[0],last_reading:dates.at(-1),model_source:'SGCC historical daily model'}}).sort((a,b)=>b.risk_score-a.risk_score)}
